"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { apiRequest } from "../../../lib/lovelydent-api";
type Patient = { id: string; fullName: string };
type Appointment = { id: string; patientName?: string; doctorName?: string; startsAt: string; status: string };
export default function DashboardPage() {
  const [patients, setPatients] = useState<Patient[]>([]); const [appointments, setAppointments] = useState<Appointment[]>([]);
  useEffect(() => { const start = new Date(); start.setHours(0,0,0,0); const end = new Date(start); end.setDate(end.getDate()+1); Promise.all([apiRequest<Patient[]>("/patients?take=100"), apiRequest<Appointment[]>(`/appointments/availability?startDate=${encodeURIComponent(start.toISOString())}&endDate=${encodeURIComponent(end.toISOString())}`)]).then(([p,a]) => { setPatients(p); setAppointments(a); }).catch(() => {}); }, []);
  return <><section className="ws-page-head"><div><p className="ws-eyebrow">Gündəlik əməliyyat görünüşü</p><h1>Sabahınız xeyir</h1><span>Bu gün klinikada diqqət tələb edən işlər burada görünür.</span></div><Link className="ws-button ws-button--primary" href="/appointments">+ Yeni qəbul</Link></section><section className="ws-metrics"><article><span>BUGÜNKÜ QƏBULLAR</span><strong>{appointments.length}</strong><small>Təqvim üzrə</small></article><article><span>PASİYENT BAZASI</span><strong>{patients.length}</strong><small>Son 100 qeyd</small></article><article><span>GÖZLƏYƏN TAPŞIRIQLAR</span><strong>—</strong><small>Tapşırıq axını hazırlanır</small></article></section><section className="ws-dashboard-grid"><article className="ws-panel ws-today"><header><div><p className="ws-eyebrow">Canlı qəbul axını</p><h2>Bu gün</h2></div><Link href="/appointments">Tam təqvim →</Link></header>{appointments.length ? appointments.slice(0,6).map((a) => <div className="ws-appointment-row" key={a.id}><time>{new Date(a.startsAt).toLocaleTimeString("az-AZ",{hour:"2-digit",minute:"2-digit"})}</time><i/><div><b>{a.patientName ?? "Pasiyent"}</b><span>{a.doctorName ?? "Həkim təyin edilməyib"}</span></div><em>{a.status}</em></div>) : <div className="ws-empty"><b>Bu gün üçün qəbul görünmür</b><span>Yeni qəbul yaradıldıqda iş axını burada görünəcək.</span></div>}</article><aside className="ws-panel ws-focus"><p className="ws-eyebrow">Növbəti addım</p><h2>Klinik iş axını</h2><p>Pasiyent kartı, anamnez və odontogramı eyni klinik kontekstdə birləşdirəcəyik.</p><Link href="/patients">Pasiyentlərə keç →</Link></aside></section></>;
}
